name: server

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd src/server
          CGO_ENABLED=0 go build -v .

      - name: Make package
        run: |
          cd src/server
          tar -zcvf selfupdate_server.tar.gz selfupdate_server

      - name: Upload Release on push tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/server/selfupdate_server.tar.gz
          asset_name: selfupdate_server_${{ github.ref_name }}.tar.gz
