name: winxp

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[no-build]') }}
    name: ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.cc_std }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        os: [windows-2019]
        arch: [x64, x86]
        cc_std: ["c++14", "c++17", "c++20", "c++latest"]
        config: [debug, release]

    steps:
      - name: Setup python environment
        run: |
          pip install PyYAML

      - name: Check out code
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          fetch_deps.bat

      - name: Fetch gn and ninja
        run: |
          python build\\fetch_binaries.py
          COPY /Y build\\bin\\* %WINDIR%\

      - name: Compile
        run: |
          gn gen out/${{ matrix.config }}_${{ matrix.arch }} --args="target_cpu=\"${{ matrix.arch }}\" cc_std=\"${{ matrix.cc_std }}\" is_debug=${{ matrix.config == 'debug' }} is_winxp=true"
          ninja -C out/${{ matrix.config }}_${{ matrix.arch }}

      - name: Unittest
        run: |
          out\\${{ matrix.config }}_${{ matrix.arch }}\\unittest
